title: lego for the blind
email: matshifrin@aol.com
url: http:/kevinyma.github.io
baseurl: /legos-for-the-blind
collections: 
  instructions:
    output: true
    permalink: /instructions/:path/
  links:
    output: true
    permalink: /links/:path/
sass:
  sass_dir: _sass
markdown: kramdown
include: ['_pages']
port: 8000
